before_install:
  - sudo apt-get install sqlite3 libsqlite3-dev python2.7-dev
language: python
python:
  - "2.6"
  - "2.7"

install: 
  - pip install -r requirements.txt
  - python manage.py create_tables  
sudo: required
os:
  - linux
  - osx

env:
  - SH=bash
