language: python

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: 2.7
        # Use generic language for osx
        - os: osx
          language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install sqlite3 libsqlite3-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-dev python-dev  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo brew update                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo brew install python sqlite   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install: 
  - pip install -r requirements.txt
  - python manage.py create_tables  

env:
  - SH=bash
script: behave comoenus/features