before_install:
  - sudo apt-get install sqlite3 libsqlite3-dev python-dev python-dev libmysqlclient-dev
language: python
python:
  - "2.6"
  - "2.7"
sudo: required
install: 
  - pip install -r requirements.txt
  - python manage.py create_tables  

os:
  - linux
  - osx

env:
  - SH=bash
script: behave comoenus/features