language: python
python: "2.7"
os: linux

before_install:
  - sudo apt-get install sqlite3 libsqlite3-dev
  - sudo apt-get install python-dev python-dev 

install: 
  - pip install -r requirements.txt
  - python manage.py create_tables  

env:
  - SH=bash

script: behave comoenus/features
